'use strict';
const S = require('../lib/services'); const cfg = require('../lib/config'); const registry = require('../lib/registry');
const C = require('./components'); const { esc, money, when, csrf, postForm, gradeBadge, statusBadge, btn, submit, tabs, panel, pager, paginate } = C;
const thumb = (t, alt) => C.thumbMissing(alt || t);

function layout(c, title, body, { flash } = {}) {
  const f = flash || c.flash;
  return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>${esc(title)} - BLOXEN</title><link rel="stylesheet" href="/static/css/bloxen.css"><link rel="stylesheet" href="/static/css/brickcolors.css"><meta name="viewport" content="width=1000"></head><body>
${C.header(c)}
<div class="nav-content">${C.leftNav(c)}<div class="notice">BLOXEN is an unofficial, non-commercial preservation project. It is not affiliated with or endorsed by Roblox Corporation.</div>
<div id="Container"><div id="BodyWrapper">${f ? `<div class="flash ${f.err ? 'err' : 'ok'}">${esc(f.text)}</div>` : ''}${body}</div></div></div>
${C.footer(cfg)}</body></html>`;
}

// ---- avatar preview. NOT a historical thumbnail: a CSS-drawn block figure of the saved body colours. Labelled as such.
function figure(colors) { const b = (w, h, c) => `<div class="p${w}x${h} bc-${S.BRICK_COLORS[c] ? c : 194}"></div>`;
  return `<div class="figure">${b(40, 40, colors.head_color)}<div class="row">${b(20, 80, colors.left_arm_color)}${b(40, 80, colors.torso_color)}${b(20, 80, colors.right_arm_color)}</div><div class="row">${b(40, 80, colors.left_leg_color)}${b(40, 80, colors.right_leg_color)}</div><div class="tip">BLOXEN colour preview &mdash; not a historical thumbnail</div></div>`; }

// Logged-out landing page. REFERENCE: a real ~2015 screenshot (Web Design Museum "Roblox in 2015", held in quarantine, not redistributed) showing
// translucent top bar with Play/About/Platforms + inline login, full-bleed hero with translucent sign-up panel, dark "What is ROBLOX?" band,
// three-screenshot strip, light-grey "ROBLOX on your device." band, large footer links. Copy is ARCHIVED-EXACT (Wayback 20150723171630).
// All photographic/brand imagery is MISSING (not retrieved) and is shown as labelled flat blocks, never substituted.
const missingImg = (cls, what) => `<div class="missing ${cls}" title="Archived image not retrieved"><span>${esc(what)}<br>(image MISSING)</span></div>`;
function landing(c, title, inner) {
  const f = c.flash;
  return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>${esc(title)} - BLOXEN</title><link rel="stylesheet" href="/static/css/bloxen.css"><link rel="stylesheet" href="/static/css/landing.css"><meta name="viewport" content="width=1000"></head><body class="landing">
<div class="notice">BLOXEN is an unofficial, non-commercial preservation project. It is not affiliated with or endorsed by Roblox Corporation.</div>${f ? `<div class="flash ${f.err ? 'err' : 'ok'}">${esc(f.text)}</div>` : ''}${inner}</body></html>`;
}
function landingBar(tok, active) {
  return `<div class="lbar"><div class="lin"><a class="llogo" href="/">BLOXEN</a><a class="ltab${active === 'play' ? ' on' : ''}" href="/games">Play</a><a class="ltab" href="/about">About</a><a class="ltab" href="/catalog">Platforms</a>
<form class="llogin" method="post" action="/login"><input type="hidden" name="_csrf" value="${esc(tok)}"><input type="text" name="username" placeholder="Username" maxlength="20" autocomplete="username"><input type="password" name="password" placeholder="Password" maxlength="200" autocomplete="current-password"><button class="lgreen" type="submit">Log In</button><div class="lforgot"><a href="/about#accounts">Forgot Username/Password?</a></div></form></div></div>`;
}
const landingFooter = () => `<div class="lfoot"><div class="lflinks"><a href="/about">About Us</a><a href="/about">Jobs</a><a href="/about">Blog</a><a href="/about">Privacy</a><a href="/about">Parents</a><a href="/about">Help</a></div>
<p>BLOXEN is an unofficial preservation project. Historical names and marks belong to their owners. Target: Windows Player ${cfg.clientBuild} (${cfg.clientVersion}). Link targets on this page are BLOXEN pages, not the 2015 originals.</p></div>`;
function homeOut(c, tok) {
  return landing(c, 'Home', `${landingBar(tok, 'play')}
<div class="lhero">${missingImg('herobg', 'Hero background photograph (images.rbxcdn.com/f76c76889f4b167ca1f27edc27eb8146.png)')}
<div class="lhero-in"><div class="ltag"><div class="lwordmark">BLOXEN</div><h1>You Make the Game <sup>&trade;</sup></h1><div class="lcredit">Game: ROBLOX Point<br>Developer: StarMarine614</div></div>
<div class="lsignup">${signupForm(c, tok)}</div></div></div>
<div class="ldark"><div class="lband">${missingImg('charimg', 'Character artwork')}<div class="ltext"><h2>What is ROBLOX?</h2><p>ROBLOX is the Game Powered by Players. Build your own game world and bring it to life, publish and share it, experience what others have created, play with friends. ROBLOX is the leader in user-generated creation and gaming for all ages. What will you build?</p></div></div></div>
<div class="lstrip">${missingImg('s1', 'Screenshot 1')}${missingImg('s2', 'Screenshot 2')}${missingImg('s3', 'Screenshot 3')}</div>
<div class="ldevice"><h2>ROBLOX on your device.</h2><p>Play ROBLOX on your desktop, your tablet, or your phone. Access your account, games, and inventory; connect with your friends; and play games whether you're at home or on the go.</p>
<div class="lbadges"><span class="lbadge">Available on the App Store</span><span class="lbadge">GET IT ON Google play</span></div>${missingImg('devimg', 'Desktop/tablet/phone artwork')}</div>
<p class="tip lnote">Copy: Wayback 20150723171630 (ARCHIVED-EXACT). Layout: reconstructed from a ~2015 screenshot. BLOXEN hosts only the evidence-backed places listed under <a href="/games">Games</a>.</p>${landingFooter()}`);
}
function signupForm(c, tok) {
  const months = ['Month', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']; const yrs = []; for (let y = 2015; y >= 1915; y--) yrs.push(y);
  return `<div class="lsu-h">Sign up and start having fun!</div><form method="post" action="/register" class="lsu"><input type="hidden" name="_csrf" value="${esc(tok)}">
<input type="text" name="username" placeholder="Username (3-20 characters, no spaces)" maxlength="20" autocomplete="off" required>
<input type="password" name="password" placeholder="Password (8+ characters)" minlength="8" maxlength="200" autocomplete="new-password" required>
<input type="password" name="confirm" placeholder="Confirm Password" required maxlength="200" autocomplete="new-password">
<div class="lsu-row"><span class="lsu-l">Birthday</span><select name="bm">${months.map((m, i) => `<option value="${i}">${m === 'Month' ? 'Month' : m}</option>`).join('')}</select><select name="bd"><option value="0">Day</option>${Array.from({ length: 31 }, (_, i) => `<option>${i + 1}</option>`).join('')}</select><select name="by"><option value="0">Year</option>${yrs.map(y => `<option>${y}</option>`).join('')}</select></div>
<div class="lsu-row"><span class="lsu-l">Gender:</span><label><input type="radio" name="gender" value="m"> Boy</label> <label><input type="radio" name="gender" value="f"> Girl</label></div>
<button class="lgreen lbig" type="submit">Sign Up</button></form><p class="lnotice">BLOXEN accounts are local. Use a NEW password &mdash; never your Roblox password.</p>`;
}
// Logged-in Home. REFERENCE: 185px-wide thumbnail "homepage from early 2015 to early 2016" (Roblox fandom wiki, quarantine copy) - grey page, blue header,
// big light-weight "Hello, <name>!" with full-body avatar at left, white Friends card with avatar tiles + light-blue "See All", RECENTLY PLAYED row of square game tiles.
// Too small to measure: proportions are estimates. Avatar/friend/game thumbnails are MISSING; the avatar is the labelled BLOXEN colour preview.
function homeIn(c, d) {
  const gameTile = g => `<div class="gtile"><a href="/games/${esc(g.id)}">${thumb('', g.title)}<div class="nm" title="${esc(g.title)}">${esc(g.title)}</div></a><div class="tip">by ${esc(g.creator || 'UNKNOWN')}</div></div>`;
  const friendTile = f => `<a class="ftile" href="/users/${f.id}/profile"><div class="fthumb">(thumbnail MISSING)</div><div class="fnm">${esc(f.username)}</div></a>`;
  return layout(c, 'Home', `<div class="hello"><div class="hello-fig">${figure(d.avatar.colors)}</div><h1 class="hello-h">Hello, ${esc(c.user.username)}!</h1></div>
<div class="card"><div class="card-h"><span>Friends (${d.friends.length})</span><a class="btn-see" href="/my/friends">See All</a></div><div class="frow">${d.friends.map(friendTile).join('') || '<span class="tip">No friends yet. <a href="/my/friends">Find some</a>.</span>'}</div></div>
<div class="sec-h"><span>RECENTLY PLAYED</span><a class="btn-see" href="/games">See All</a></div>${d.recent.length ? `<div class="grow">${d.recent.map(gameTile).join('')}</div>` : '<p class="tip">You have not played anything yet.</p>'}
<div class="sec-h"><span>MY FAVORITES</span><a class="btn-see" href="/games">See All</a></div>${d.favs.length ? `<div class="grow">${d.favs.map(gameTile).join('')}</div>` : '<p class="tip">No favorite games yet.</p>'}
<p>${d.unread ? `<a href="/my/messages"><b>${d.unread} unread message${d.unread > 1 ? 's' : ''}</b></a>` : ''}</p><p class="tip"><a href="/my/character">Customize Character</a></p>`);
}
// ---- Games list (2015 page: sort tabs + tile grid). Only sorts BLOXEN has real data for are offered; the archived places carry no genre/play statistics.
function games(c, list, { sort = 'default', favs = {}, statuses = {} } = {}) {
  const tile = g => C.gameTile(g, { fav: favs[g.id] || 0, status: statuses[g.id] });
  const tb = [{ label: 'Default', href: '/games', selected: sort === 'default' }, { label: 'Top Favorite', href: '/games?sort=favorite', selected: sort === 'favorite' }, ...(c.user ? [{ label: 'Recently Played', href: '/games?sort=recent', selected: sort === 'recent' }] : []), { label: 'Game Registry', href: '/games/registry' }];
  return layout(c, 'Games', `<h1>Games</h1>${tabs(tb)}
<p class="tip">Every game listed is a place file BLOXEN holds that has registry status PRESERVED (public-release evidence recorded). Popular/Top Earning/Top Rated/Genre filters from the 2015 page are not offered: the archived places carry no play, earning, rating or genre data. See the <a href="/games/registry">Game Registry</a> for every place considered, including those not offered.</p>
<div class="grow">${list.map(tile).join('') || '<p class="tip">Nothing to show.</p>'}</div>`);
}
function gameRegistry(c, { rows, status, counts, pg }) {
  const tb = [{ label: `All (${Object.values(counts).reduce((a, b) => a + b, 0)})`, href: '/games/registry', selected: !status }, ...Object.entries(counts).map(([s, n]) => ({ label: `${s} (${n})`, href: `/games/registry?status=${s}`, selected: status === s }))];
  return layout(c, 'Game Registry', `<h1>Game Registry</h1>${tabs(tb)}<p class="tip">PRESERVED = bytes held and public-release evidence recorded (says nothing about playability). QUARANTINED = provenance or era unresolved. REJECTED = must not be used. UNKNOWN = listed in the source archive, never evaluated; a clean parse does not promote it. Only PRESERVED places are offered on the Games page.</p>
<table class="t"><tr><th>Status</th><th>Name</th><th>Creator</th><th>Basis</th></tr>${rows.map(r => `<tr><td>${statusBadge(r.status)}</td><td>${r.status === 'PRESERVED' ? `<a href="/games/${esc(r.id)}">${esc(r.title)}</a>` : esc(r.title)}</td><td>${esc(r.creator)}</td><td class="tip">${esc(String(r.basis || '').slice(0, 220))}</td></tr>`).join('')}</table>
${pager({ ...pg, hrefFn: p => `/games/registry?${status ? `status=${encodeURIComponent(status)}&` : ''}page=${p}` })}`);
}
function gameDetails(c, g, d) {
  const ev = JSON.parse(g.evidence || '[]'); const st = JSON.parse(g.stats || '{}'); const src = JSON.parse(g.source || '{}'); const reg = d.registry; const rep = d.report; const pl = d.playability;
  const play = !c.user ? `${btn('Play', { href: `/login?next=/games/${esc(g.id)}`, size: 'large' })}<div class="tip">Log in to play</div>`
    : pl.eligible ? postForm(c, `/games/${esc(g.id)}/play`, submit('Play', { size: 'large' })) : `${btn('Play', { size: 'large', disabled: true, title: pl.reason })}<div class="tip">Not playable: ${esc(pl.reason)}</div>`;
  const tab = d.tab;
  const about = `<div class="StandardPanelWhite"><div class="pn-h">Status</div><div class="pn-b"><p>Registry: ${reg ? statusBadge(reg.status) : statusBadge('UNKNOWN')} &nbsp; Playability: <span class="badge y">${esc(pl.level)}</span> &nbsp; Real client: <span class="badge r">NOT TESTED</span></p><p>${esc(reg ? reg.basis : '')}</p>
<p>${esc(pl.reason)}</p><p class="tip">${st.scripts ? `This place's ${st.scripts} script(s) are stored as inert data; BLOXEN's sandboxed Lua runtime is off by default and is not a faithful engine, so the game's original logic is not claimed to work.` : 'This place contains no scripts.'}</p></div></div>
<div class="StandardPanelWhite"><div class="pn-h">Provenance</div><div class="pn-b"><table class="t prov"><tr><td>Grade</td><td>${gradeBadge(g.grade)}</td></tr><tr><td>SHA-256</td><td class="mono">${esc(g.sha256)}</td></tr><tr><td>Source</td><td class="mono">${esc(src.repo)} @ ${esc(src.commit)}</td></tr></table><p class="tip">Full evidence is on the Evidence tab.</p></div></div>
<div class="StandardPanelWhite"><div class="pn-h">Running Games</div><div class="pn-b">${d.running ? `One local BLOXEN server is running: ${d.running.players} / 12 players, started ${new Date(d.running.startedAt).toISOString().replace('T', ' ').slice(0, 19)} UTC.` : 'No local server is running. Pressing Play starts one (loopback only).'}</div></div>`;
  const compat = rep ? `<table class="t prov"><tr><td>Overall</td><td>${esc(rep.overall)} <span class="tip">(static analysis; ${esc(rep.tested.REAL_CLIENT)})</span></td></tr><tr><td>Importer</td><td>geometry ${esc(rep.importerCompat.geometry)} &middot; terrain ${esc(rep.importerCompat.terrain)} &middot; scripts ${esc(rep.importerCompat.scripts)} &middot; GUI ${esc(rep.importerCompat.gui)} &middot; assets ${esc(rep.importerCompat.assets)}</td></tr>
<tr><td>Contents</td><td>${rep.instances} instances, ${rep.parts} parts, ${rep.meshes} meshes, ${rep.sounds} sounds, ${rep.guis} GUIs</td></tr><tr><td>Replication</td><td>${rep.replication.imported} instances replicate; ${rep.replication.serverOnlyDropped} server-only dropped; ${rep.replication.unknownClassDropped} unknown-class dropped${rep.replication.topDroppedClasses.length ? ' (' + esc(rep.replication.topDroppedClasses.join(', ')) + ')' : ''}</td></tr>
<tr><td>Scripts</td><td>${rep.scripts.total} total ${esc(JSON.stringify(rep.scripts.byClass))}; sandbox status ${esc(JSON.stringify(rep.scripts.sandboxStatusCounts))}; ${rep.scripts.touchedConnections} Touched connection(s)${rep.scripts.unsupportedApis.length ? '; unsupported APIs: ' + esc(rep.scripts.unsupportedApis.join(', ')) : ''}</td></tr>
<tr><td>Assets</td><td>${rep.assets.distinctReferences} asset-id reference(s), ${rep.assets.clientBuiltin} client-built-in. ${esc(rep.assets.note)}</td></tr>${rep.teleportDestinations.length ? `<tr><td>Teleports</td><td>${rep.teleportDestinations.map(t => `PlaceId ${t.robloxPlaceId}: ${esc(t.result)}${t.local ? ' &rarr; ' + esc(t.local) : ''}`).join('<br>')}</td></tr>` : ''}
<tr><td>Blockers</td><td><ul>${rep.blockers.map(b => `<li>${esc(b)}</li>`).join('')}</ul></td></tr><tr><td>Tested</td><td>UNIT-TESTED: yes. SIMULATOR-TESTED: ${esc(rep.tested.SIMULATOR)}. REAL-CLIENT-TESTED: no.</td></tr></table>` : '<p class="tip">No compatibility report has been generated for this place (run tools/build_compat_reports.js).</p>';
  const evidence = `<table class="t prov"><tr><td>Provenance grade</td><td>${gradeBadge(g.grade)}</td></tr><tr><td>Tier / status</td><td>${esc(g.tier)} / ${esc(g.status)}</td></tr><tr><td>Date</td><td>${esc(g.date_note)}</td></tr><tr><td>Public/uncopylocked evidence</td><td>${esc(g.public_evidence)}</td></tr><tr><td>Acquisition method</td><td>${esc(g.method)}</td></tr>
<tr><td>Source</td><td class="mono">${esc(src.repo)} @ ${esc(src.commit)}<br>${esc(src.path)}</td></tr><tr><td>SHA-256</td><td class="mono">${esc(g.sha256)}</td></tr><tr><td>Format / size</td><td>${esc(g.format)} / ${money(g.size)} bytes</td></tr><tr><td>Importer compatibility</td><td>${esc(g.compat)}</td></tr>
<tr><td>Evidence</td><td><ul>${ev.map(e => `<li>${esc(e)}</li>`).join('')}</ul></td></tr>${g.notes ? `<tr><td>Notes</td><td>${esc(g.notes)}</td></tr>` : ''}</table>`;
  const tb = [['about', 'About'], ['compat', 'Compatibility'], ['evidence', 'Evidence']].map(([k, n]) => ({ label: n, href: `/games/${g.id}?tab=${k}`, selected: tab === k }));
  return layout(c, g.title, `<div id="GameDetails"><h1>${esc(g.title)}</h1><div class="by">By <b>${esc(g.creator)}</b>${g.roblox_place_id ? ` &middot; original place ID ${g.roblox_place_id}` : ''}</div>
<div class="two"><div class="side2">${thumb('', g.title)}<div class="gd-play">${play}</div><div class="gd-fav">${c.user ? postForm(c, `/games/${esc(g.id)}/favorite`, `<input type="hidden" name="on" value="${d.fav ? 0 : 1}"><button class="favstar${d.fav ? ' on' : ''}" title="${d.fav ? 'Unfavorite' : 'Favorite'}">&#9733;</button>`) : '<span class="favstar">&#9733;</span>'} <span class="stat-label">Favorited</span> <b>${d.favCount}</b> <span class="tip">(local)</span></div>
<ul class="gd-stats"><li><span class="stat-label">Launches</span> ${d.launches} <span class="tip">(this BLOXEN install)</span></li><li><span class="stat-label">Max Players</span> 12 <span class="tip">(BLOXEN cap)</span></li><li><span class="stat-label">Genre</span> UNKNOWN</li><li><span class="stat-label">Dated</span> ${esc(g.date_note)}</li><li><span class="stat-label">Uncopylocked</span> evidence recorded (Evidence tab)</li></ul></div>
<div class="main">${tabs(tb)}${tab === 'compat' ? compat : tab === 'evidence' ? evidence : about}</div></div></div>`);
}
function travel(c, rows) {
  return layout(c, 'Travel', `<h1>Travel</h1><p class="tip">When a game you are in teleports you to another historical place that BLOXEN holds, it is recorded here. Continue starts a normal, fresh launch ticket for that place (single use, 60 seconds). Teleport destinations BLOXEN does not hold are never forwarded anywhere; they are refused.</p>
<table class="t"><tr><th>From</th><th>To</th><th>When</th><th></th></tr>${rows.map(r => `<tr><td>${esc(r.from_title || r.from_place)}</td><td>${esc(r.to_title || r.to_place)}${r.roblox_place_id ? ` <span class="tip">(PlaceId ${r.roblox_place_id})</span>` : ''}</td><td>${new Date(r.created_at).toISOString().replace('T', ' ').slice(0, 19)} UTC</td><td>${postForm(c, `/my/travel/${r.id}/continue`, submit('Continue', { size: 'small' }))} ${postForm(c, `/my/travel/${r.id}/dismiss`, submit('Dismiss', { size: 'small', kind: 'negative' }))}</td></tr>`).join('') || '<tr><td colspan="4" class="tip">No pending travel.</td></tr>'}</table>`);
}
function favorites(c, d) {
  const cats = [[0, 'All Items'], ...CATS.slice(1)];
  return layout(c, 'Favorites', `<h1>My Favorites</h1><h2 class="light">Games</h2><div class="grow">${d.places.map(g => C.gameTile(g)).join('') || '<p class="tip">No favorite games yet.</p>'}</div>
<h2 class="light">Catalog items</h2>${tabs(cats.map(([id, n]) => ({ label: n, href: `/my/favorites?type=${id}`, selected: +d.type === id })))}<div class="grid">${d.items.map(i => C.itemTile(i)).join('') || '<p class="tip">No favorite items.</p>'}</div>`);
}
const CATS = [[0, 'All'], [8, 'Hats'], [18, 'Faces'], [2, 'T-Shirts'], [11, 'Shirts'], [12, 'Pants'], [17, 'Heads'], [19, 'Gear'], [32, 'Packages']];
const PER_CATALOG = 24;
function catalog(c, items, q, pg) {
  const base = p => `/catalog?type=${+q.type || 0}${q.q ? '&q=' + encodeURIComponent(q.q) : ''}&sort=${encodeURIComponent(q.sort || 'relevance')}&page=${p}`;
  return layout(c, 'Catalog', `<h1>Catalog</h1><div class="two"><div class="side"><div class="StandardPanelWhite"><div class="pn-h">Category</div><div class="pn-b">${CATS.map(([id, n]) => `<div><a href="/catalog?type=${id}${q.q ? '&q=' + encodeURIComponent(q.q) : ''}" ${+q.type === id ? 'class="b"' : ''}>${n}</a></div>`).join('')}</div></div>
<p class="tip">Items shown are from archived 2015 catalog feeds (ARCHIVED-NEAR-DATE: 2015-03-09 and 2015-06-16). Only those captured are listed; BLOXEN does not invent catalog entries. Thumbnails and asset files were not retrieved (MISSING).</p></div>
<div class="main"><form method="get" action="/catalog" class="cat-search"><input type="hidden" name="type" value="${+q.type || 0}"><input type="text" name="q" value="${esc(q.q || '')}" maxlength="60" placeholder="Search Catalog"> <select name="sort">${[['relevance', 'Relevance'], ['updated', 'Recently Updated'], ['price_asc', 'Price (Low to High)'], ['price_desc', 'Price (High to Low)']].map(([v, n]) => `<option value="${v}"${q.sort === v ? ' selected' : ''}>${n}</option>`).join('')}</select> <button class="btn-small btn-neutral">Search</button></form>
<p class="tip">${pg.total} item(s)</p><div class="grid">${items.map(i => C.itemTile(i)).join('')}</div>${pager({ ...pg, hrefFn: base })}</div></div>`);
}
function catalogItem(c, i, d) {
  const price = i.price_robux != null ? `<span class="robux-text">R$ ${money(i.price_robux)}</span>` : i.price_tickets != null ? `<span class="price t">Tickets ${money(i.price_tickets)}</span>` : '<span class="stat-label">Off sale</span>';
  const offSale = i.price_robux == null && i.price_tickets == null; const wearable = ['T-Shirt', 'Hat', 'Shirt', 'Pants', 'Head', 'Face', 'Package'].includes(i.type);
  const act = offSale && !(c.user && d.owned) ? '<span class="badge r">Off Sale</span>' : !c.user ? btn('Buy', { href: `/login?next=/catalog/item/${i.asset_id}` }) : d.owned ? `<span class="badge g">Item Owned</span> ${wearable ? postForm(c, `/my/character/equip`, `<input type="hidden" name="asset" value="${i.asset_id}">${submit('Wear', { kind: 'neutral' })}`) : ''}` : i.min_membership > 0 ? '<span class="badge r">Builders Club only</span>' : (i.limited_unique || i.resale_only) ? `<span class="badge r">${i.limited_unique ? 'Sold Out (Limited U)' : 'Limited: resale only'}</span>` : postForm(c, `/catalog/item/${i.asset_id}/buy`, submit('Buy'));
  const fav = c.user ? postForm(c, `/catalog/item/${i.asset_id}/favorite`, `<input type="hidden" name="on" value="${d.fav ? 0 : 1}"><button class="favstar${d.fav ? ' on' : ''}" title="${d.fav ? 'Unfavorite' : 'Favorite'}">&#9733;</button>`) : '<span class="favstar">&#9733;</span>';
  return layout(c, i.name, `<div id="Item"><h1>${esc(i.name)}</h1><div class="two"><div id="Thumbnail">${thumb('', i.name)}<div class="it-fav">${fav} <span class="stat-label">Favorited</span> <b>${d.favCount}</b> <span class="tip">(local; archive: ${esc(i.favorited)})</span></div></div>
<div id="Summary"><div class="stat-label">${esc(i.type)} &middot; Creator: <b>${esc(i.creator)}</b> (ID ${i.creator_id})</div><p>${esc(i.description)}</p><div class="BuyPriceBox"><div class="stat-label">Price:</div> ${price} ${i.limited_unique ? '<span class="badge y">Limited U</span>' : ''}<div class="BuyAct">${act}</div></div>
<h2 class="light">Archive record</h2><table class="t prov"><tr><td>Asset ID</td><td>${i.asset_id}</td></tr><tr><td>Created / Updated</td><td>${when(i.created_ms)} / ${when(i.updated_ms)}</td></tr><tr><td>Sales / Favorited</td><td>${esc(i.sales)} / ${esc(i.favorited)} <span class="tip">(as of the capture)</span></td></tr><tr><td>Source capture</td><td class="mono">Wayback ${esc(i.source_capture)} &mdash; catalog/json</td></tr><tr><td>Provenance grade</td><td>${gradeBadge(i.provenance)}</td></tr><tr><td>Asset content</td><td><span class="badge r">${esc(d.asset.availability)}</span> ${esc(d.asset.note || '')}</td></tr><tr><td>Thumbnail</td><td><span class="badge r">${esc(i.thumbnail)}</span></td></tr></table></div></div></div>`);
}
const PROFILE_FAV_CATS = [['places', 'Places'], ...CATS.slice(1).map(([id, n]) => [String(id), n])];
function profile(c, u, d) {
  const favSel = d.favCat || 'places';
  const favBody = favSel === 'places' ? `<div class="grow">${d.favPlaces.map(g => C.gameTile(g)).join('') || '<span class="tip">None</span>'}</div>` : `<div class="grid">${d.favItems.map(i => C.itemTile(i)).join('') || '<span class="tip">None</span>'}</div>`;
  return layout(c, u.username, `<div id="Profile"><h1>${esc(u.username)}'s Profile</h1><div class="tip">[ ${d.online ? 'Online' : 'Offline'} ]</div><div class="two"><div class="side2">${figure(d.avatar.colors)}<p class="tc">${d.friendBtn}</p></div><div class="main"><div class="StandardPanelWhite"><div class="pn-h">About</div><div class="pn-b"><p>${esc(u.blurb) || '<span class="tip">No blurb.</span>'}</p><div class="tip">Member since ${when(u.created_at)}</div></div></div>
<div class="StandardPanelWhite"><div class="pn-h">${esc(u.username)}'s Friends (${d.friends.length})</div><div class="pn-b">${d.friends.map(f => `<a href="/users/${f.id}/profile">${esc(f.username)}</a>`).join(', ') || '<span class="tip">None</span>'}</div></div>
<div class="StandardPanelWhite"><div class="pn-h">Groups</div><div class="pn-b">${d.groups.map(g => `<a href="/groups/${g.id}">${esc(g.name)}</a>`).join(', ') || '<span class="tip">None</span>'}</div></div>
<div class="StandardPanelWhite"><div class="pn-h">Currently wearing</div><div class="pn-b">${d.avatar.items.map(i => `<a href="/catalog/item/${i.asset_id}">${esc(i.name)}</a>`).join(', ') || '<span class="tip">Nothing</span>'}</div></div>
<div class="StandardPanelWhite"><div class="pn-h">Favorites</div><div class="pn-b"><form method="get" action="/users/${u.id}/profile" class="fav-cat"><label>Category <select name="fav">${PROFILE_FAV_CATS.map(([k, n]) => `<option value="${k}"${k === favSel ? ' selected' : ''}>${n}</option>`).join('')}</select></label> <button class="btn-small btn-neutral">Show</button></form>${favBody}</div></div>${d.msg}</div></div></div>`);
}
function character(c, d) {
  const { colors, items } = d.avatar; const parts = [['head_color', 'Head'], ['torso_color', 'Torso'], ['left_arm_color', 'Left Arm'], ['right_arm_color', 'Right Arm'], ['left_leg_color', 'Left Leg'], ['right_leg_color', 'Right Leg']];
  const sw = (part, cur) => Object.entries(S.BRICK_COLORS).map(([id, [n, hex]]) => postForm(c, '/my/character/color', `<input type="hidden" name="part" value="${part}"><input type="hidden" name="color" value="${id}"><button title="${esc(n)}" class="sw bc-${id}${+id === cur ? ' cur' : ''}"></button>`)).join('');
  return layout(c, 'Character', `<h1>Avatar</h1><div class="two"><div class="side2">${figure(colors)}<p class="tip">This is what the game server receives: body colours and worn assets. Asset content that is MISSING is skipped, never substituted.</p></div><div class="main">
<h2 class="light">Currently Wearing</h2><table class="t">${items.map(i => `<tr><td><a href="/catalog/item/${i.asset_id}">${esc(i.name)}</a></td><td>${esc(i.type)}</td><td>${postForm(c, '/my/character/remove', `<input type="hidden" name="asset" value="${i.asset_id}"><button class="btn-small btn-negative">Remove</button>`)}</td></tr>`).join('') || '<tr><td class="tip">Nothing worn. Buy items in the <a href="/catalog">Catalog</a>.</td></tr>'}</table>
<h2 class="light">Body Colors</h2>${parts.map(([k, n]) => `<div><b>${n}</b> ${sw(k, colors[k])}</div>`).join('')}
<h2 class="light">Wardrobe</h2><div class="grid">${d.inv.filter(i => ['T-Shirt', 'Hat', 'Shirt', 'Pants', 'Head', 'Face', 'Package'].includes(i.type)).map(i => `<div class="tile"><div class="nm">${esc(i.name)}</div><div class="tip">${esc(i.type)}</div>${postForm(c, '/my/character/equip', `<input type="hidden" name="asset" value="${i.asset_id}"><button class="btn-small btn-neutral">Wear</button>`)}</div>`).join('') || '<span class="tip">Your wardrobe is empty.</span>'}</div></div></div>`);
}
function inventory(c, d) {
  const total = Object.values(d.counts).reduce((a, b) => a + b, 0);
  const wearable = ['T-Shirt', 'Hat', 'Shirt', 'Pants', 'Head', 'Face', 'Package'];
  return layout(c, 'Inventory', `<h1>Inventory</h1><div class="two"><div class="side"><div class="StandardPanelWhite"><div class="pn-h">Category</div><div class="pn-b">${CATS.map(([id, n]) => `<div><a href="/my/inventory?type=${id}" ${+d.type === id ? 'class="b"' : ''}>${n}</a> <span class="tip">(${id ? d.counts[id] || 0 : total})</span></div>`).join('')}<p class="tip">Places, Models, Decals and Audio categories exist on the 2015 site because users could upload; BLOXEN has no uploads.</p></div></div></div>
<div class="main"><div class="grid">${d.items.map(i => `<div class="tile"><a href="/catalog/item/${i.asset_id}">${thumb('', i.name)}<div class="nm" title="${esc(i.name)}">${esc(i.name)}</div></a><div class="tip">${esc(i.type)}</div>${wearable.includes(i.type) ? postForm(c, '/my/character/equip', `<input type="hidden" name="asset" value="${i.asset_id}">${submit('Wear', { size: 'small', kind: 'neutral' })}`) : ''}</div>`).join('') || '<p class="tip">Nothing here.</p>'}</div>${pager({ ...d.pg, hrefFn: p => `/my/inventory?type=${+d.type || 0}&page=${p}` })}</div></div>`);
}
function people(c, q, r, pg) {
  return layout(c, 'People', `<h1>People</h1><form method="get" action="/users" class="cat-search"><input type="text" name="q" value="${esc(q)}" maxlength="40" placeholder="Search for a username"> <button class="btn-small btn-neutral">Search</button></form><p class="tip">${r.total} user(s)</p><div class="frow">${r.users.map(C.userTile).join('')}</div>${pager({ ...pg, hrefFn: p => `/users?q=${encodeURIComponent(q)}&page=${p}` })}`);
}
function friends(c, d) {
  return layout(c, 'Friends', `<h1>Friends</h1><div class="two"><div class="main"><h2 class="light">Friends (${d.friends.length})</h2><table class="t">${d.friends.map(f => `<tr><td><a href="/users/${f.id}/profile">${esc(f.username)}</a></td><td>${postForm(c, '/my/friends/remove', `<input type="hidden" name="id" value="${f.id}"><button class="btn-small btn-negative">Unfriend</button>`)}</td></tr>`).join('') || '<tr><td class="tip">No friends yet.</td></tr>'}</table>
<h2 class="light">Friend Requests (${d.requests.length})</h2><table class="t">${d.requests.map(r => `<tr><td><a href="/users/${r.id}/profile">${esc(r.username)}</a></td><td>${postForm(c, '/my/friends/respond', `<input type="hidden" name="id" value="${r.id}"><input type="hidden" name="accept" value="1"><button class="btn-small btn-primary">Accept</button>`)} ${postForm(c, '/my/friends/respond', `<input type="hidden" name="id" value="${r.id}"><input type="hidden" name="accept" value="0"><button class="btn-small btn-negative">Decline</button>`)}</td></tr>`).join('') || '<tr><td class="tip">None</td></tr>'}</table></div>
<div class="side"><div class="box"><h3>Add a friend</h3>${postForm(c, '/my/friends/request', '<input type="text" name="username" maxlength="20" placeholder="Username"> <button class="btn-small btn-neutral">Send</button>')}</div></div></div>`);
}
function groups(c, d) { return layout(c, 'Groups', `<h1>Groups</h1><div class="two"><div class="main"><h2 class="light">My Groups</h2><table class="t">${d.mine.map(g => `<tr><td><a href="/groups/${g.id}">${esc(g.name)}</a></td><td>${esc(g.role)}</td></tr>`).join('') || '<tr><td class="tip">You are not in any groups.</td></tr>'}</table><h2 class="light">All Groups</h2><table class="t">${d.all.map(g => `<tr><td><a href="/groups/${g.id}">${esc(g.name)}</a></td><td>${g.members} member(s)</td></tr>`).join('') || '<tr><td class="tip">No groups exist yet.</td></tr>'}</table></div>
<div class="side"><div class="box"><h3>Create a Group</h3>${postForm(c, '/my/groups/create', '<label>Name</label><input type="text" name="name" maxlength="40"><label>Description</label><textarea name="description" maxlength="1000" class="w230"></textarea><p><button class="btn-small btn-primary">Create</button></p>', 'stack')}</div></div></div>`); }
function group(c, g, d) { return layout(c, g.name, `<h1>${esc(g.name)}</h1><p>${esc(g.description)}</p><p class="tip">Owner: ${esc(d.owner.username)}</p>${c.user && !d.member ? postForm(c, `/groups/${g.id}/join`, '<button class="btn-medium btn-primary">Join Group</button>') : ''}<h2 class="light">Members</h2><p>${d.members.map(m => `<a href="/users/${m.id}/profile">${esc(m.username)}</a> (${esc(m.role)})`).join(', ')}</p>`); }
function develop(c, list, all) {
  return layout(c, 'Develop', `<h1>Develop</h1><p>Place intake for BLOXEN. Every candidate goes through: quarantine &rarr; SHA-256 &rarr; static parse &rarr; instance tree &rarr; scripts as inert data &rarr; asset IDs &rarr; compatibility report. <b>Scripts are never executed during intake.</b> Uploading is not offered: places come only from the evidence-reviewed manifest (<span class="mono">preservation/manifests/places.json</span>).</p>
<table class="t"><tr><th>Place</th><th>Tier</th><th>Status</th><th>Grade</th><th>Compat</th><th>SHA-256</th></tr>${all.map(p => `<tr><td>${/^ACCEPTED/.test(p.status) ? `<a href="/games/${esc(p.id)}">${esc(p.title)}</a>` : esc(p.title)}</td><td>${esc(p.tier)}</td><td><span class="badge ${/^ACCEPTED/.test(p.status) ? 'g' : 'r'}">${esc(p.status)}</span></td><td>${esc(p.grade)}</td><td>${esc(p.compat)}</td><td class="mono">${esc(String(p.sha256).slice(0, 16))}&hellip;</td></tr>`).join('')}</table><p class="tip">QUARANTINED and REJECTED items are listed for transparency and are never offered as games.</p>`);
}
function messages(c, d, compose) {
  return layout(c, 'Messages', `<h1>Messages</h1><div class="tabs"><a class="sel" href="/my/messages">Inbox</a></div><table class="t"><tr><th>From</th><th>Subject</th><th>Date</th></tr>${d.msgs.map(m => `<tr class="msg${m.read ? '' : ' unread'}"><td>${esc(m.from_name)}</td><td><a href="/my/messages/${m.id}">${esc(m.subject)}</a></td><td>${when(m.created_at)}</td></tr>`).join('') || '<tr><td colspan="3" class="tip">No messages.</td></tr>'}</table><h2 class="light">Send a message</h2>${postForm(c, '/my/messages/send', `<label>To</label><input type="text" name="to" maxlength="20" value="${esc(compose?.to || '')}"><label>Subject</label><input type="text" name="subject" maxlength="100"><label>Message</label><textarea name="body" maxlength="5000"></textarea><p><button class="btn-medium btn-primary">Send</button></p>`, 'stack')}`);
}
function message(c, m) { return layout(c, m.subject, `<h1>${esc(m.subject)}</h1><p class="tip">From ${esc(m.from_name)} &middot; ${when(m.created_at)}</p><pre class="ev">${esc(m.body)}</pre><p><a href="/my/messages?to=${encodeURIComponent(m.from_name)}">Reply</a></p>`); }
function searchPage(c, q, r) { const l = (arr, f) => arr.length ? `<ul>${arr.map(f).join('')}</ul>` : '<p class="tip">No results.</p>'; return layout(c, 'Search', `<h1>Search: ${esc(q)}</h1><h2 class="light">Games</h2>${l(r.games, g => `<li><a href="/games/${esc(g.id)}">${esc(g.title)}</a> by ${esc(g.creator)}</li>`)}<h2 class="light">Catalog</h2>${l(r.items, i => `<li><a href="/catalog/item/${i.asset_id}">${esc(i.name)}</a> (${esc(i.type)})</li>`)}<h2 class="light">Users</h2>${l(r.users, u => `<li><a href="/users/${u.id}/profile">${esc(u.username)}</a></li>`)}<h2 class="light">Groups</h2>${l(r.groups, g => `<li><a href="/groups/${g.id}">${esc(g.name)}</a></li>`)}`); }
function login(c, tok, next) { return landing(c, 'Login', `${landingBar(tok, '')}<div class="lhero lhero-short">${missingImg('herobg', 'Background photograph')}<div class="lhero-in"><div class="ltag"><div class="lwordmark">BLOXEN</div></div><div class="lsignup"><div class="lsu-h">Log in</div><form method="post" action="/login" class="lsu"><input type="hidden" name="_csrf" value="${esc(tok)}"><input type="hidden" name="next" value="${esc(next || '')}"><input type="text" name="username" placeholder="Username" maxlength="20" autocomplete="username"><input type="password" name="password" placeholder="Password" maxlength="200" autocomplete="current-password"><button class="lgreen lbig" type="submit">Log In</button></form><p class="lnotice">BLOXEN accounts are local. Never enter a Roblox password here. <a href="/register">Sign up</a></p></div></div></div>${landingFooter()}`); }
function register(c, tok) { return landing(c, 'Sign Up', `${landingBar(tok, '')}<div class="lhero lhero-short">${missingImg('herobg', 'Background photograph')}<div class="lhero-in"><div class="ltag"><div class="lwordmark">BLOXEN</div><h1>You Make the Game <sup>&trade;</sup></h1></div><div class="lsignup">${signupForm(c, tok)}</div></div></div>${landingFooter()}`); }
function account(c) { const u = c.user; return layout(c, 'Account Settings', `<h1>Account Settings</h1><div class="box"><h3>Account Info</h3><table class="t prov"><tr><td>Username</td><td>${esc(u.username)}</td></tr><tr><td>Birthday</td><td>${esc(u.birthday || 'not set')}</td></tr><tr><td>Member since</td><td>${when(u.created_at)}</td></tr></table></div>
<div class="box"><h3>Blurb</h3>${postForm(c, '/my/account/blurb', `<textarea name="blurb" maxlength="1000" class="w440">${esc(u.blurb)}</textarea><p><button class="btn-small btn-neutral">Save</button></p>`, 'stack')}</div>
<div class="box"><h3>Change Password</h3>${postForm(c, '/my/account/password', '<label>Current password</label><input type="password" name="current" maxlength="200" autocomplete="current-password"><label>New password</label><input type="password" name="password" maxlength="200" autocomplete="new-password"><p><button class="btn-small btn-neutral">Change</button></p>', 'stack')}</div>
<div class="box"><h3>Sessions</h3>${postForm(c, '/my/account/logout-all', '<button class="btn-small btn-negative">Log out everywhere</button>')}</div>`); }
function launchPage(c, g, uri) { return layout(c, 'Starting ' + g.title, `<h1>Starting ${esc(g.title)}&hellip;</h1><p>Your one-time launch ticket was created (valid 60 seconds, single use, bound to your account and this game). Click to hand it to the BLOXEN launcher:</p><p><a class="btn-large btn-primary" href="${esc(uri)}">Launch BLOXEN Player</a></p><p class="tip">Requires the BLOXEN launcher registered for the <span class="mono">bloxen-player:</span> protocol and the reviewed client ${esc(cfg.clientBuild)} (see docs/WINDOWS-REAL-CLIENT-VALIDATION.md). Without it nothing will happen.</p><p><a href="/games/${esc(g.id)}">Back to ${esc(g.title)}</a></p>`); }
function about(c) { return layout(c, 'About', `<h1>About BLOXEN</h1><p>BLOXEN is an unofficial, non-commercial preservation and research project that reconstructs the July 2015 Roblox experience from archived evidence. It is not Roblox and is not affiliated with Roblox Corporation.</p><ul><li>Every historical component carries a provenance grade: PRESERVED, ARCHIVED-EXACT, ARCHIVED-NEAR-DATE, RECONSTRUCTED-FROM-EVIDENCE, INFERRED or UNKNOWN.</li><li>Missing assets stay MISSING; nothing homemade is presented as historical.</li><li>The currency shown (R$) is a local BLOXEN play allowance, not a historical economy.</li></ul>`); }
function notFound(c) { return layout(c, 'Not Found', '<h1>Page not found</h1><p><a href="/">Home</a></p>'); }
module.exports = { postForm, gameRegistry, travel, favorites, people, layout, homeOut, homeIn, games, gameDetails, catalog, catalogItem, profile, character, inventory, friends, groups, group, develop, messages, message, searchPage, login, register, account, launchPage, about, notFound, figure };
