// Regenerates static/css/brickcolors.css from S.BRICK_COLORS (hex values INFERRED - see docs/ASSETS.md / CATALOG.md).
const S = require('../src/lib/services'); const fs = require('fs'); const path = require('path');
fs.writeFileSync(path.join(__dirname, '..', 'static', 'css', 'brickcolors.css'), '/* generated by tools/gen_brickcolors_css.js - BrickColor hex values are INFERRED, not archived */\n' + Object.entries(S.BRICK_COLORS).map(([id, [, hex]]) => `.bc-${id} { background: ${hex}; }`).join('\n') + '\n');
