#!/usr/bin/env node
'use strict';
// Script index: one row per script instance of every registry-PRESERVED place held in the local store.
//   place, instance name, hierarchy path, class, SHA-256 of the source, referenced services, referenced asset ids, referenced place ids,
//   compatibility findings, execution status under the BLOXEN sandbox.
// Static scan + a short SANDBOXED run (virtual time, no players, no network). Nothing runs outside src/script; source text is NOT written out, only hashes.
// usage: node --disable-warning=ExperimentalWarning tools/script_index.js [virtualSeconds=30]
const fs = require('fs'); const path = require('path'); const crypto = require('crypto');
const { parsePlace } = require('../src/importer/parse'); const { World } = require('../src/gameserver/world'); const { ScriptHost } = require('../src/script/engine'); const { API } = require('../src/importer/analyze');
const root = path.join(__dirname, '..'); const secs = +(process.argv[2] || 30); const reg = require('../src/lib/registry'); const placemap = require('../src/lib/placemap');
const SERVICES = new Set(Object.entries(API.classes).filter(([, c]) => c.tags.includes('Service')).map(([n]) => n));
const PATTERNS = { http: /HttpService|HttpGet|HttpPost|GetAsync|PostAsync/, loadstring: /loadstring|getfenv|setfenv/, require: /\brequire\s*\(/, insertservice: /InsertService|LoadAsset/, datastore: /DataStoreService|GetDataStore/, marketplace: /MarketplaceService|PromptPurchase|PlayerOwnsAsset|UserOwnsGamePass/, teleport: /TeleportService|\bTeleport\s*\(/, badges: /BadgeService|AwardBadge/, remote: /RemoteEvent|RemoteFunction|FireServer|FireClient|OnServerEvent/, gui: /\bScreenGui\b|\bTextLabel\b|\bTextButton\b|\bFrame\b|\bMessage\b|\bHint\b/, tool: /\bTool\b|Equipped|Unequipped|Activated/, bodymovers: /Body(Velocity|Position|Gyro|Force|Thrust)|RocketPropulsion/, obfuscated: /\\\d{3}\\\d{3}\\\d{3}|string\.char\s*\(\s*\d+\s*,\s*\d+/, kick: /:Kick\(|\.Kick\(/, touched: /\bTouched\b/ };
const ASSET_RES = [/rbxassetid:\/\/(\d+)/g, /roblox\.com\/asset\/?\?id=(\d+)/gi, /[?&]assetId=(\d+)/gi, /[?&]id=(\d{3,})/g];
const services = src => { const s = new Set(); for (const m of src.matchAll(/(?:GetService|getService|service|Service)\s*\(\s*["']([A-Za-z]+)["']\s*\)/g)) s.add(m[1]); for (const m of src.matchAll(/\bgame\s*\.\s*([A-Z][A-Za-z]+)/g)) if (SERVICES.has(m[1])) s.add(m[1]); for (const m of src.matchAll(/\bgame\s*:\s*(?:GetService|service)/g)) { /* covered above */ } if (/\bworkspace\b/.test(src)) s.add('Workspace'); return [...s].sort(); };
const assets = src => { const s = new Set(); for (const re of ASSET_RES) { re.lastIndex = 0; for (const m of src.matchAll(re)) s.add(m[1]); } return [...s].sort((a, b) => a - b); };
const walkTree = (w, f) => { f(w); for (const c of w.children) walkTree(c, f); for (const c of w.shadowKids || []) walkTree(c, f); };
const out = { schema: 'bloxen.script-index/1', generated: new Date().toISOString().slice(0, 10), virtualSeconds: secs, note: 'Static scan + sandboxed virtual-time run. executionStatus is about the BLOXEN sandbox, NOT real Roblox behaviour. Source text is not stored; sourceSha256 identifies it. Duplicate hierarchy paths are distinguished by "occurrence".', totals: { places: 0, scripts: 0 }, places: {} };
for (const r of reg.registry().filter(x => x.status === 'PRESERVED')) {
  const file = path.join(root, 'preservation', 'store', r.sha256 + '.rbx'); if (!fs.existsSync(file)) { out.places[r.id] = { registryStatus: r.status, placeSha256: r.sha256, skipped: 'place file not in local store' }; continue; }
  const world = new World({ place: parsePlace(fs.readFileSync(file)), respawnSeconds: 0.01 }); const host = new ScriptHost(world, {}).start(); for (let t = 0; t < secs; t++) host.step(1);
  const rep = host.report(); const seen = {}; const rows = [];
  world.scriptSources.forEach((src, i) => { const p = host._path(src); seen[p] = (seen[p] || 0) + 1; const rec = rep.scripts[i] || {}; const text = src.source || '';
    const findings = Object.entries(PATTERNS).filter(([, re]) => re.test(text)).map(([k]) => k); const refs = [];
    // place-id references: numeric TeleportService arguments, and PlaceId-named IntValues next to or under the script
    for (const m of text.matchAll(/Teleport\w*\s*\(\s*(\d{2,})/g)) refs.push(+m[1]); const scan = w => walkTree(w, n => { if (/PlaceId$/i.test(n.name) && typeof n.props.get('Value') === 'number') refs.push(n.props.get('Value')); });
    if (src.shadow) scan(src.shadow); if (src.parent) for (const k of src.parent.children.concat(src.parent.shadowKids || [])) if (k !== src.shadow && /PlaceId$/i.test(k.name) && typeof k.props.get('Value') === 'number') refs.push(k.props.get('Value')); if (src.parent && src.parent.parent) for (const k of src.parent.parent.children) if (/PlaceId$/i.test(k.name) && typeof k.props.get('Value') === 'number') refs.push(k.props.get('Value'));
    const placeIds = [...new Set(refs)].sort((a, b) => a - b); const teleportTargets = placeIds.map(id => ({ robloxPlaceId: id, ...(({ result, local, reason }) => ({ result, local, reason }))(placemap.resolve(id, { storeHas: () => true })) }));
    rows.push({ place: r.id, name: src.name, path: p, occurrence: seen[p], class: src.className, sourceBytes: Buffer.byteLength(text), sourceSha256: crypto.createHash('sha256').update(text).digest('hex'), disabled: src.disabled, referencedServices: services(text), referencedAssetIds: assets(text), referencedPlaceIds: placeIds, teleportTargets: teleportTargets.length ? teleportTargets : undefined, compatFindings: findings, executionStatus: rec.status || 'unknown', executionError: rec.error || undefined }); });
  // scripts nested under other scripts are not in world.scriptSources (their parent is not imported); they are still data: index them as never-run children
  world.scriptSources.forEach(src => { if (!src.shadow) return; const base = host._path(src); const nest = (w, p) => { for (const c of w.children) { const cp = p + '.' + c.name; if (typeof c.sourceText === 'string') { const text = c.sourceText; seen[cp] = (seen[cp] || 0) + 1; const refs = []; for (const m of text.matchAll(/Teleport\w*\s*\(\s*(\d{2,})/g)) refs.push(+m[1]); walkTree(c, n => { if (/PlaceId$/i.test(n.name) && typeof n.props.get('Value') === 'number') refs.push(n.props.get('Value')); }); const placeIds = [...new Set(refs)].sort((a, b) => a - b);
        rows.push({ place: r.id, name: c.name, path: cp, occurrence: seen[cp], class: c.className, sourceBytes: Buffer.byteLength(text), sourceSha256: crypto.createHash('sha256').update(text).digest('hex'), disabled: c.props.get('Disabled') === true, referencedServices: services(text), referencedAssetIds: assets(text), referencedPlaceIds: placeIds, teleportTargets: placeIds.length ? placeIds.map(id => ({ robloxPlaceId: id, ...(({ result, local, reason }) => ({ result, local, reason }))(placemap.resolve(id, { storeHas: () => true })) })) : undefined, compatFindings: Object.entries(PATTERNS).filter(([, re]) => re.test(text)).map(([k]) => k), executionStatus: c.className === 'LocalScript' ? 'not-run:client-side script (nested under a script)' : 'not-run:nested under a script (not imported as a runnable script)' }); } nest(c, cp); } }; nest(src.shadow, base); });
  const byStatus = rows.reduce((a, s) => (a[s.executionStatus] = (a[s.executionStatus] || 0) + 1, a), {});
  out.places[r.id] = { registryStatus: r.status, placeSha256: r.sha256, scripts: rows.length, executionStatusCounts: byStatus, unsupportedApis: rep.unsupported, teleportLog: host.teleportLog.length, rows }; out.totals.places++; out.totals.scripts += rows.length;
}
fs.writeFileSync(path.join(root, 'research', 'script-index.json'), JSON.stringify(out, null, 1) + '\n');
const md = ['# Script index', '', `Generated by \`tools/script_index.js\` (${out.generated}; ${secs} s of virtual sandbox time). Machine-readable data: \`research/script-index.json\` — one row per script instance: place, name, hierarchy path, class, source SHA-256, referenced services, referenced asset IDs, referenced place IDs (+ how each resolves under the local PlaceId mapping), compatibility findings, execution status.`, '', '**Execution status is a statement about the BLOXEN sandbox (UNIT/SIMULATOR evidence). It says nothing about how the original script behaved on Roblox, and no place is claimed playable.** Script source text is never stored here; only SHA-256.', '', `Totals: ${out.totals.scripts} scripts across ${out.totals.places} places.`, '', '| Place | Scripts | Execution status counts | Teleport references |', '|---|---:|---|---|'];
for (const [id, p] of Object.entries(out.places)) { if (p.skipped) { md.push(`| ${id} | – | ${p.skipped} | – |`); continue; } const tp = [...new Set(p.rows.flatMap(s => (s.teleportTargets || []).map(t => `${t.robloxPlaceId}→${t.local || 'unsupported-local-destination'}`)))]; md.push(`| ${id} | ${p.scripts} | ${Object.entries(p.executionStatusCounts).map(([k, v]) => `${k}: ${v}`).join(', ') || '–'} | ${tp.join(', ') || '–'} |`); }
md.push('', '## Findings legend', '', 'Compat findings are lexical (regex) hits: `http`, `loadstring`, `require`, `insertservice`, `datastore`, `marketplace`, `teleport`, `badges`, `remote`, `gui`, `tool`, `bodymovers`, `obfuscated`, `kick`, `touched`. A hit means "the text mentions it", not that it is exercised.', '');
fs.writeFileSync(path.join(root, 'research', 'SCRIPT-INDEX.md'), md.join('\n'));
console.log(md.slice(6, 6 + 10 + Object.keys(out.places).length).join('\n'));
